vich_uploader:
    db_driver: orm

    mappings:
       users:
           uri_prefix: /images/users
           upload_destination: '%kernel.project_dir%/public/images/users'
           namer: Vich\UploaderBundle\Naming\UniqidNamer  # pour ajouter un uniq id à chaque image

           # conditions si l'images est mise à jour

           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true
